name: Publish

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: sbt

      - name: Setup sbt
        uses: sbt/setup-sbt@v1

      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        run: sbt +core/publish
